"""AI PG 초기 스키마 — 06_erd.md 26테이블 (D-② 커밋③).

ERD가 정본이며, 이 마이그레이션 본문은 ai.db.models 의 metadata 에서 결정론적으로
생성했다(CreateTableOp.from_table + render_python_code) — 손으로 옮기지 않아 드리프트가
원천 차단된다. 실명·연락처 컬럼 없음(불변식 3), enum 은 varchar + 앱 검증.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-07-22
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_run',
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('capability', sa.String(), nullable=False),
    sa.Column('pipeline_version', sa.String(), nullable=False),
    sa.Column('engine_version', sa.String(), nullable=False),
    sa.Column('threshold_version', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.Column('contract_version', sa.String(), nullable=False),
    sa.Column('graph_version', sa.String(), nullable=True),
    sa.Column('taxonomy_version', sa.String(), nullable=True),
    sa.Column('verify_config_version', sa.String(), nullable=True),
    sa.Column('difficulty_calib_version', sa.String(), nullable=True),
    sa.Column('model_provider', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('generation_params', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('input_snapshot_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('execution_id', name=op.f('pk_ai_run'))
    )
    op.create_table('baseline',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('student_ref', sa.String(), nullable=False),
    sa.Column('segment', sa.String(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('window_weeks', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_baseline'))
    )
    op.create_table('engine_registry',
    sa.Column('engine_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('feature_schema', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('engine_id', name=op.f('pk_engine_registry'))
    )
    op.create_table('evidence_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('owner_kind', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('source_table', sa.String(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_item'))
    )
    op.create_table('feature_week',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('student_ref', sa.String(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('segment', sa.String(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('feature_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_week')),
    sa.UniqueConstraint('tenant_id', 'student_ref', 'week_start', 'feature_version', name='uq_feature_week_scope')
    )
    op.create_table('gate_result',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('owner_kind', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('gate_name', sa.String(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gate_result'))
    )
    op.create_table('idempotency_record',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('snapshot_hash', sa.String(), nullable=False),
    sa.Column('response_body', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_record')),
    sa.UniqueConstraint('tenant_id', 'endpoint', 'idempotency_key', name='uq_idempotency_scope')
    )
    op.create_table('label_suggestion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('guardian_ref', sa.String(), nullable=False),
    sa.Column('axis', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('evidence_quotes', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('confidence', sa.Numeric(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_label_suggestion'))
    )
    op.create_table('rule_feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('alert_ref', sa.String(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_feedback'))
    )
    op.create_table('source_profile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('sheets', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_profile'))
    )
    op.create_table('style_profile',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', name=op.f('pk_style_profile'))
    )
    op.create_table('threshold_config',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('approved_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_threshold_config'))
    )
    op.create_table('agent_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('agent_kind', sa.String(), nullable=False),
    sa.Column('state_checkpoint', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('progress', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['ai_run.execution_id'], name=op.f('fk_agent_run_run_id_ai_run')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_run'))
    )
    op.create_table('draft',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('agent_run_id', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('student_ref', sa.String(), nullable=False),
    sa.Column('guardian_ref', sa.String(), nullable=False),
    sa.Column('label_snapshot', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('fail_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['ai_run.execution_id'], name=op.f('fk_draft_run_id_ai_run')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_draft'))
    )
    op.create_table('llm_call',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('prompt_id', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['ai_run.execution_id'], name=op.f('fk_llm_call_run_id_ai_run')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_call'))
    )
    op.create_table('mapping_spec',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('source_profile_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('spec', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('inferred_by_call', sa.Uuid(), nullable=True),
    sa.Column('probe_agent_run', sa.Uuid(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_profile_id'], ['source_profile.id'], name=op.f('fk_mapping_spec_source_profile_id_source_profile')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mapping_spec'))
    )
    op.create_table('signal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('student_ref', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('signal_type', sa.String(), nullable=False),
    sa.Column('display_label', sa.String(), nullable=False),
    sa.Column('lifecycle', sa.String(), nullable=False),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['ai_run.execution_id'], name=op.f('fk_signal_run_id_ai_run')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signal'))
    )
    op.create_table('agent_step',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_run_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('node_name', sa.String(), nullable=False),
    sa.Column('tool_called', sa.String(), nullable=True),
    sa.Column('tool_args_masked', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('llm_call_id', sa.Uuid(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_run.id'], name=op.f('fk_agent_step_agent_run_id_agent_run')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_step'))
    )
    op.create_table('draft_block',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('draft_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('regen_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['draft.id'], name=op.f('fk_draft_block_draft_id_draft')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_draft_block'))
    )
    op.create_table('draft_revision',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('draft_id', sa.Uuid(), nullable=False),
    sa.Column('turn_no', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('block_seq', sa.Integer(), nullable=True),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('preset', sa.String(), nullable=True),
    sa.Column('result_blocks', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('gates_passed', sa.Boolean(), nullable=False),
    sa.Column('blocked_reason', sa.String(), nullable=True),
    sa.Column('llm_call_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['draft.id'], name=op.f('fk_draft_revision_draft_id_draft')),
    sa.ForeignKeyConstraint(['llm_call_id'], ['llm_call.id'], name=op.f('fk_draft_revision_llm_call_id_llm_call')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_draft_revision'))
    )
    op.create_table('import_job',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('spec_id', sa.Uuid(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('row_total', sa.Integer(), nullable=False),
    sa.Column('row_ok', sa.Integer(), nullable=False),
    sa.Column('row_fail', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['spec_id'], ['mapping_spec.id'], name=op.f('fk_import_job_spec_id_mapping_spec')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_job'))
    )
    op.create_table('inquiry_class',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('inquiry_ref', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('urgency', sa.String(), nullable=False),
    sa.Column('confidence', sa.Numeric(), nullable=False),
    sa.Column('corrected_by_teacher', sa.Boolean(), nullable=False),
    sa.Column('llm_call_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['llm_call_id'], ['llm_call.id'], name=op.f('fk_inquiry_class_llm_call_id_llm_call')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inquiry_class'))
    )
    op.create_table('llm_payload',
    sa.Column('call_id', sa.Uuid(), nullable=False),
    sa.Column('request_masked', sa.Text(), nullable=False),
    sa.Column('response_raw', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['llm_call.id'], name=op.f('fk_llm_payload_call_id_llm_call')),
    sa.PrimaryKeyConstraint('call_id', name=op.f('pk_llm_payload'))
    )
    op.create_table('signal_brief',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('signal_ref', sa.Uuid(), nullable=False),
    sa.Column('brief_text', sa.Text(), nullable=False),
    sa.Column('gate_passed', sa.Boolean(), nullable=False),
    sa.Column('fallback_used', sa.Boolean(), nullable=False),
    sa.Column('llm_call_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['llm_call_id'], ['llm_call.id'], name=op.f('fk_signal_brief_llm_call_id_llm_call')),
    sa.ForeignKeyConstraint(['signal_ref'], ['signal.id'], name=op.f('fk_signal_brief_signal_ref_signal')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signal_brief'))
    )
    op.create_table('tag_suggestion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('source_text_hash', sa.String(), nullable=False),
    sa.Column('source_kind', sa.String(), nullable=False),
    sa.Column('area_tag', sa.String(), nullable=False),
    sa.Column('type_tag', sa.String(), nullable=False),
    sa.Column('confidence', sa.Numeric(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('llm_call_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['llm_call_id'], ['llm_call.id'], name=op.f('fk_tag_suggestion_llm_call_id_llm_call')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tag_suggestion'))
    )
    op.create_table('import_row_error',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=False),
    sa.Column('column_name', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['import_job.id'], name=op.f('fk_import_row_error_job_id_import_job')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_row_error'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('import_row_error')
    op.drop_table('tag_suggestion')
    op.drop_table('signal_brief')
    op.drop_table('llm_payload')
    op.drop_table('inquiry_class')
    op.drop_table('import_job')
    op.drop_table('draft_revision')
    op.drop_table('draft_block')
    op.drop_table('agent_step')
    op.drop_table('signal')
    op.drop_table('mapping_spec')
    op.drop_table('llm_call')
    op.drop_table('draft')
    op.drop_table('agent_run')
    op.drop_table('threshold_config')
    op.drop_table('style_profile')
    op.drop_table('source_profile')
    op.drop_table('rule_feedback')
    op.drop_table('label_suggestion')
    op.drop_table('idempotency_record')
    op.drop_table('gate_result')
    op.drop_table('feature_week')
    op.drop_table('evidence_item')
    op.drop_table('engine_registry')
    op.drop_table('baseline')
    op.drop_table('ai_run')
    # ### end Alembic commands ###
